name:                quick-segment-search
version:             0.1.0.0
github:              "syamasak/quick-segment-search"
license:             BSD3
author:              "syamasak"
maintainer:          "shuto.yamasaki@cern.ch"
copyright:           "2018 syamasak"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/syamasak/quick-segment-search#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- trifecta
- parsers
- lens
- unix
- filepath

library:
  source-dirs: src

executables:
  genparam:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quick-segment-search

# tests:
#   quick-segment-search-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - quick-segment-search-test
